## The following functions are used to optimise repeated (computatinoally-expensive) matrix inverse calculations.
## This is achieved by the use of caching, where once a value is calculated, it is stored in a list for retrieval in futture calculations.


## Creates a special "cacheMatrix" from a supplied matrix object.
## "cacheMatrix" objects are a list contain get and set methods for the value of the matrix and its inverse

makeCacheMatrix <- function(x = matrix()) {

	inverse <- NULL
    set <- function(y) {
            x <<- y
            inverse <<- NULL
    }
    get <- function() x

    setinverse <- function(inv) inverse <<- inv
    getinverse <- function() inverse
   
    list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


## Calculates the inverse of a square invertible matrix, using caching.
## If the inverse has been calculated previously, it is retrieved from the cache
## Otherwise, the value is calculated and cached
## x must be a "cacheMatrix" object (list) as generated by makeCacheMatrix function 

cacheSolve <- function(x, ...) {
    inverse <- x$getinverse()
    if(!is.null(inverse)) {
        message("retrieving data from cache")
        return(inverse)
    }

	matrix <- x$get()
	inverse <- solve(matrix, ...)
	x$setinverse(inverse)
    inverse
}

